name: flutter_jr_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter_lints: ^2.0.0
  cloud_firestore: ^5.6.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.2
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  gap: ^3.0.0
  intl: ^0.20.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5


dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
